model: cvae3d

paths:
  checkpoint_dir: checkpoints
  log_dir: logs
  output_dir: outs

data:
  train_csv: ""             
  val_csv: ""               
  cond_csv: ""              
  label: "high"
  use_embeddings: true
  ignore_embeddings: true
  build_3d: true            # set true if your CSV lacks 3D; ETKDG will be used
  num_workers: 4
  pin_memory: true

training:
  epochs: 80
  batch_size: 16
  lr: 1.0e-4
  weight_decay: 0.0
  grad_clip: 1.0
  scheduler: cosine
  step_size: 20
  gamma: 0.5
  seed: 42
  deterministic: false
  device: "cuda"

model_cfg:
  embed_dim: 128
  latent_dim: 64
  hidden_dim: 256
  grid_size: 24
  num_atom_types: 5         # e.g., [C,N,O,F,S] (keep in post-processing too)

generation:
  num_samples: 100
  voxel_threshold: 0.5
  nms_radius: 1
  bond_threshold: 1.65      # Å for naive bonding in postprocess
