model: equifm

paths:
  checkpoint_dir: checkpoints_equifm
  log_dir: logs_equifm
  output_dir: outs_equifm

data:
  train_csv: ""             
  val_csv: ""               
  cond_csv: ""              
  label: "high"
  use_embeddings: true
  ignore_embeddings: true
  build_3d: true            # needs 3D or will build via ETKDG
  num_workers: 4
  pin_memory: true

training:
  epochs: 100
  batch_size: 8
  lr: 2.0e-4
  weight_decay: 0.0
  grad_clip: 1.0
  scheduler: cosine
  step_size: 20
  gamma: 0.5
  seed: 42
  deterministic: false
  device: "cpu"

model_cfg:
  embed_dim: 128
  hidden_dim: 128
  num_atom_types: 5

# optional (used by equifm trainer/sampler if implemented)
flow_matching:
  n_time_samples: 8

generation:
  num_samples: 100
  sampler: heun            # [heun, euler]
  steps: 80
  step_size: 0.08
  num_atoms: 12
  bond_threshold: 1.65
