model: graphvae

paths:
  checkpoint_dir: checkpoints
  log_dir: logs
  output_dir: outs

data:
  train_csv: ""             # fill for training/finetune
  val_csv: ""               # optional
  cond_csv: ""              # fill for generation/eval
  label: "high"
  use_embeddings: true
  ignore_embeddings: true  # set true ONLY for unconditional pretrain (SMILES-only)
  build_3d: false
  num_workers: 0
  pin_memory: false

training:
  epochs: 50
  batch_size: 64
  lr: 1.0e-3
  weight_decay: 0.0
  grad_clip: 1.0
  scheduler: cosine
  step_size: 20
  gamma: 0.5
  seed: 42
  deterministic: false
  device: "cpu"

model_cfg:
  embed_dim: 128
  latent_dim: 64
  hidden_dim: 128
  max_nodes: 64
  node_feat_dim: 6          # e.g. [C,N,O,F,S,Stop]

# optional (used by graphvae trainer if implemented)
kl_anneal:
  beta_start: 0.0
  beta_end: 1.0
  warmup_epochs: 10

generation:
  num_samples: 200
